route book availabe
WildCodeSchool/2023-09-JS-Lille-GeoCode pull request #22
Opened 2024-01-24 10:50 UTC by Bravax

2024-01-24 12:23 UTC, ItsMatDev approved these changes

2024-01-24 12:25 UTC, ItsMatDev requested changes

2024-01-24 12:25 UTC, ItsMatDev commented on backend/src/models/BookAvailable.js
> +      .query(`SELECT date, charge_point_id, car_id,
remove this ,

2024-01-24 13:52 UTC, Yoann-Fortin approved these changes

2024-01-24 15:09 UTC, Bravax commented on backend/src/models/BookAvailable.js
> +      .query(`SELECT date, charge_point_id, car_id,
Modified

2024-01-25 08:16 UTC, SebSamPro requested changes
need changes

2024-01-25 09:16 UTC, closed without merging