css fixes
WildCodeSchool/2023-09-JS-Lille-GeoCode pull request #34
Opened 2024-01-31 09:06 UTC by JulienOza

2024-02-05 09:53 UTC, ItsMatDev requested changes

2024-02-05 09:53 UTC, ItsMatDev commented on frontend/src/components/StationMiniCard/StationMiniCard.jsx
refixing

2024-02-05 10:50 UTC, Bravax approved these changes

2024-02-05 10:52 UTC, SebSamPro approved these changes

2024-02-05 15:23 UTC, Yoann-Fortin approved these changes

2024-02-06 14:04 UTC, ItsMatDev approved these changes

2024-02-06 14:11 UTC, merged