Created home page + composant button
WildCodeSchool/2023-09-JS-Lille-GeoCode pull request #4
Opened 2023-12-21 14:16 UTC by Bravax

2023-12-21 16:20 UTC, ItsMatDev requested changes

2023-12-21 16:20 UTC, ItsMatDev commented on frontend/src/pages/Home/NavigationButton.scss
> +  border-radius: 0.5rem 3rem;
use px instead of rem for border

2023-12-21 16:20 UTC, ItsMatDev commented on frontend/src/pages/Home/NavigationButton.scss
> +  border: 0.15rem solid black;
px instead of rem

2023-12-22 08:17 UTC, Bravax commented on frontend/src/pages/Home/NavigationButton.scss
> +  border-radius: 0.5rem 3rem;
Amended

2023-12-22 08:17 UTC, Bravax commented on frontend/src/pages/Home/NavigationButton.scss
> +  border: 0.15rem solid black;
Amended

2024-01-04 14:42 UTC, Yoann-Fortin approved these changes

2024-01-04 14:59 UTC, ItsMatDev approved these changes

2024-01-04 14:59 UTC, ItsMatDev commented on frontend/src/pages/Home/NavigationButton.jsx
> +    <div className="styleButton">
no div here, use button instead, see if link wrap button or button wrap link

2024-01-04 14:59 UTC, ItsMatDev commented on frontend/src/pages/Home/NavigationButton.scss
> +  margin-bottom: 3%;
use vh instead of %

2024-01-04 14:59 UTC, ItsMatDev commented on frontend/src/pages/Home/NavigationButton.scss
> +  box-shadow: 0px 4px 4px 0px rgba(0, 0, 0, 0.25);
not good here but we will change it later with variable comming in an other PR

2024-01-04 15:00 UTC, JulienOza approved these changes

2024-01-04 15:13 UTC, SebSamPro approved these changes

2024-01-04 15:15 UTC, merged