S02 subscribe
WildCodeSchool/2023-09-JS-Lille-GeoCode pull request #5
Opened 2023-12-21 15:49 UTC by SebSamPro

2023-12-21 16:11 UTC, ItsMatDev approved these changes

2023-12-21 16:11 UTC, ItsMatDev commented on frontend/src/assets/arrowBackDark.png
remove png and keep only svg

2024-01-05 12:46 UTC, Yoann-Fortin requested changes

2024-01-05 12:46 UTC, Yoann-Fortin commented on frontend/src/components/BackButton/Redirection.jsx
> +    <button type="button" onClick={() => navigate(-1)}>
Isn't a button but a link

2024-01-05 12:46 UTC, Yoann-Fortin commented on frontend/src/pages/Subscribe/Subscribe.jsx
Wrong semantic

2024-01-05 12:46 UTC, Yoann-Fortin commented on frontend/src/pages/Subscribe/Subscribe.scss
> +  display: none;
Why display none ?

2024-01-06 16:43 UTC, closed without merging